config/routes.rb
Rails.application.routes.draw do

  get 'home/index'
  root "home#index"
  get 'home/services'

  get "projects", to: "projects#index"

  resources :clients
  resources :films
  resources :tvs
  resources :marketings
  resources :indie_films
  #resources :musicology_services
  resources :staffs
  resources :contacts, only: [:index]

  get "/login" => "sessions#new", as: "login"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy", as: "logout"

end

app/models/admin.rb
class Admin < ActiveRecord::Base

  has_secure_password

end

app/models/client.rb
class Client < ActiveRecord::Base
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
end

app/models/film.rb
class Film < ActiveRecord::Base
  belongs_to :project

  # after_save :check_for_and_create_favorite

  def change_favorite
    self.favorite = false if self.favorite = true
    self.favorite = true if self.favorite = false
  end

  def check_for_and_create_favorite
    if self.favorite == true && self.favorite_changed? == true
      Favorite.create(title: self.title,
                          year: self.year,
                   description: self.description,
                       img_url: self.img_url)
    elsif self.favorite == false && self.favorite_changed? == true
      favorite = Favorite.find_by(title: self.title,
                                   year: self.year,
                            description: self.description,
                                img_url: self.img_url)
      # favorite.destroy
    elsif
      self.favorite == true && self.favorite_changed? == false
      favorite = Favorite.find_by(title: self.title)

      favorite.update(title: self.title,
                        year: self.year,
                description: self.description,
                    img_url: self.img_url)
    end
  end
end

app/models/indie_film.rb
class IndieFilm < ActiveRecord::Base
end

app/models/marketing.rb
class Marketing < ActiveRecord::Base

  belongs_to :project
  after_save :check_for_and_create_favorite

  def change_favorite
    self.favorite = false if self.favorite = true
    self.favorite = true if self.favorite = false
  end

  def check_for_and_create_favorite
    if self.favorite == true && self.favorite_changed? == true
      Favorite.create(title: self.title,
                          year: self.year,
                   description: self.description,
                       img_url: self.img_url)
    elsif self.favorite == false && self.favorite_changed? == true
      favorite = Favorite.find_by(title: self.title,
                                   year: self.year,
                            description: self.description,
                                img_url: self.img_url)
      # favorite.destroy
    elsif
      self.favorite == true && self.favorite_changed? == false
      favorite = Favorite.find_by(title: self.title)
                  favorite.update(title: self.title,
                                   year: self.year,
                            description: self.description,
                                img_url: self.img_url)
    end
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
    has_many :tvs
    has_many :films
    has_many :marketings
    has_many :indie_films

    # def create_object(object)
    #   if object == "tv"
    #     self.tv.new(tv_params)
    #   elsif object == "film"
    #     self.tv.net(film_params)
    #   elsif object == "independednt_films"
    #     self.tv.net(independednt_films_params)
    # end

end

app/models/season.rb
class Season < ActiveRecord::Base
  belongs_to :tv
  before_save :check_image_url

  def check_image_url
    tv = Tv.find_by(id: self.tv_id)
    if self.img_url == nil
      self.img_url = tv.img_url
    end
  end

  def return_favorites
    array = []
    self.each do |object|
      if object.favorite == true
        array << object
      end
    end
    return array
  end

end

app/models/staff.rb
class Staff < ActiveRecord::Base
end

app/models/tv.rb
class Tv < ActiveRecord::Base
  belongs_to :project

  # after_save :check_for_and_create_favorite

  def change_favorite
    self.favorite = false if self.favorite = true
    self.favorite = true if self.favorite = false
  end

  def check_for_and_create_favorite
    if self.favorite == true && self.favorite_changed? == true
      Favorite.create(title: self.title,
                          year: self.year,
                   description: self.description,
                       img_url: self.img_url)
    elsif self.favorite == false && self.favorite_changed? == true
      favorite = Favorite.find_by(title: self.title,
                                   year: self.year,
                            description: self.description,
                                img_url: self.img_url)
      # favorite.destroy
    elsif
      self.favorite == true && self.favorite_changed? == false
      favorite = Favorite.find_by(title: self.title)

      favorite.update(title: self.title,
                        year: self.year,
                description: self.description,
                    img_url: self.img_url)
    end
  end
end

app/controllers/tvs_controller.rb
class TvsController < ApplicationController
  before_action :set_tv, only: [:show, :edit, :update, :destroy]

  def index
    @tvs = Tv.all
  end

  def show
  end

  def new
    @tv = Tv.new
  end

  def edit
  end

  def create
    @tv = Tv.new(tv_params)

    respond_to do |format|
      if @tv.save
        format.html { redirect_to @tv, notice: 'TV Show was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end


  def update
    respond_to do |format|
      if @tv.update(tv_params)
        format.html { redirect_to @tv, notice: 'TV Show was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @tv.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'TV Show was successfully destroyed.' }
    end
  end

  private
    def set_tv
      @tv = Tv.find(params[:id])
    end

    def tv_params

      params.require(:tv).permit(:year, :title, :network, :season, :description, :img_url, :favorite)
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper

	def show_film
    @film = Film.find_by(title: params[:title])
  end


end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/staff_helper.rb
module StaffHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/tv_helper.rb
module TvHelper
end

app/views/tvs/_form.html.erb
<%= form_for(@tv) do |f| %>
  <div class="modal_box">
    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :year %><br>
      <%= f.text_field :year %>
    </div>
    <div class="field">
      <%= f.label :season %><br>
      <%= f.text_field :season %>
    </div>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_area :description,  class: "materialize-textarea" %>
    </div>
    <div class="field">
      <%= f.label :img_url %><br>
      <%= f.text_field :img_url %>
    </div>
    <div class="field">
      <%= f.label :network %><br>
      <%= f.text_field :network %>
    </div>
    <div class="field center">
      <%= f.check_box :favorite, {:class => "filled-in"} %>
      <%= f.label :favorite %>
    </div>
    <div class="actions center">
      <%= f.submit "Save", class: "btn" %>  or
      <%= link_to "Cancel", projects_url, class: "btn" %></div>
    </div>
  </div>
<% end %>

app/views/tvs/_index.html.erb
<h1>TV Shows</h1>
  <div class="container project_frame">
    <div class="row valign">
      <% @tvs.each do |tv| %>
        <div class="col s12 m6 l3 center">
        <div class="poster_index">
          <%= link_to image_tag(tv.img_url, :class => "poster_thumb"), tv %>
        </div>
        <div class="info">
          <div class="title_box">
          <h5>
          <% if tv.favorite == true %>
            <span class="fa fa-star secondary"></span>
          <% end %>
          <%= truncate(tv.title, :length => 50, :separator => ' ') %>
          </h5>
          <h6>
            <% if tv.year == nil %>
              <%= "Coming Soon" %>
            <% end %>

            <%= tv.year %>
          </h6>
          <!-- <h6> <span class="network_name_index"> <%= tv.network %></span></h6> -->
        </div>
        </div>

        <div class="admin_box">
          <% if current_admin %>
            <%= link_to '<span class="fa fa-edit"></span> Edit'.html_safe, edit_tv_path(tv) %> |
            <%= link_to '<span class="fa fa-remove"></span> Remove'.html_safe, tv, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </div>
        </div>
      <% end %>
    </div>
  </div>

<div class="admin_box">
  <% if current_admin %>
    <%= link_to '<span class="fa fa-plus"></span> New TV Show'.html_safe, new_tv_path, :class => "btn valign" %>
  <% end %>
</div>

app/views/tvs/edit.html.erb
<div class="main_primary">
<h1 class="white-txt">Edit TV Show</h1>
	<div class="container-form">
	  <div class="form">
		<%= render 'form' %>
		<!-- <%= render "shared/formatting"  %> -->
		</div>
	</div>
</div>

app/views/tvs/new.html.erb
<div class="main_primary">
<h1 class="white-txt">New TV Show</h1>
	<div class="container-form">
	  <div class="form">
		<%= render 'form' %>
		<!-- <%= render "shared/formatting"  %> -->
		</div>
	</div>
</div>

app/views/tvs/show.html.erb
<div class="film_frame">
	<div class="show_poster"><%= link_to image_tag(@tv.img_url, :class => "poster")%></div>

	<h1>
	  <% if @tv.favorite == true %>
	  <span class="fa fa-star secondary"></span>
	  <% end %>
	  <%= @tv.title %> <br>
	<span class="network_name"> (<%= @tv.network %>)</span><br>
	<span class="year"> <%= @tv.year %> - Season <%= @tv.season %></span> </h1>
	<div class="divider"></div>
	<p> <%= markdown(@tv.description) %> </p>

	<div class="divider"></div>

	<div class="admin_box">
	  <%= link_to '<span class="fa fa-arrow-left"></span> Back'.html_safe, projects_path %>
	  <% if current_admin %>
	     | <%= link_to '<span class="fa fa-edit"></span> Edit'.html_safe, edit_tv_path(@tv) %>
	  <% end %>
	</div>

</div>