config/routes.rb
Rails.application.routes.draw do

  get 'home/index'
  root "home#index"
  get 'home/services'

  get "projects", to: "projects#index"

  resources :clients
  resources :films
  resources :tvs
  resources :marketings
  resources :indie_films
  #resources :musicology_services
  resources :staffs
  resources :contacts, only: [:index]

  get "/login" => "sessions#new", as: "login"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy", as: "logout"

end

app/models/admin.rb
class Admin < ActiveRecord::Base

  has_secure_password

end

app/models/client.rb
class Client < ActiveRecord::Base
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
end

app/models/film.rb
class Film < ActiveRecord::Base
  belongs_to :project

  # after_save :check_for_and_create_favorite

  def change_favorite
    self.favorite = false if self.favorite = true
    self.favorite = true if self.favorite = false
  end

  def check_for_and_create_favorite
    if self.favorite == true && self.favorite_changed? == true
      Favorite.create(title: self.title,
                          year: self.year,
                   description: self.description,
                       img_url: self.img_url)
    elsif self.favorite == false && self.favorite_changed? == true
      favorite = Favorite.find_by(title: self.title,
                                   year: self.year,
                            description: self.description,
                                img_url: self.img_url)
      # favorite.destroy
    elsif
      self.favorite == true && self.favorite_changed? == false
      favorite = Favorite.find_by(title: self.title)

      favorite.update(title: self.title,
                        year: self.year,
                description: self.description,
                    img_url: self.img_url)
    end
  end
end

app/models/indie_film.rb
class IndieFilm < ActiveRecord::Base
end

app/models/marketing.rb
class Marketing < ActiveRecord::Base

  belongs_to :project
  after_save :check_for_and_create_favorite

  def change_favorite
    self.favorite = false if self.favorite = true
    self.favorite = true if self.favorite = false
  end

  def check_for_and_create_favorite
    if self.favorite == true && self.favorite_changed? == true
      Favorite.create(title: self.title,
                          year: self.year,
                   description: self.description,
                       img_url: self.img_url)
    elsif self.favorite == false && self.favorite_changed? == true
      favorite = Favorite.find_by(title: self.title,
                                   year: self.year,
                            description: self.description,
                                img_url: self.img_url)
      # favorite.destroy
    elsif
      self.favorite == true && self.favorite_changed? == false
      favorite = Favorite.find_by(title: self.title)
                  favorite.update(title: self.title,
                                   year: self.year,
                            description: self.description,
                                img_url: self.img_url)
    end
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
    has_many :tvs
    has_many :films
    has_many :marketings
    has_many :indie_films

    # def create_object(object)
    #   if object == "tv"
    #     self.tv.new(tv_params)
    #   elsif object == "film"
    #     self.tv.net(film_params)
    #   elsif object == "independednt_films"
    #     self.tv.net(independednt_films_params)
    # end

end

app/models/season.rb
class Season < ActiveRecord::Base
  belongs_to :tv
  before_save :check_image_url

  def check_image_url
    tv = Tv.find_by(id: self.tv_id)
    if self.img_url == nil
      self.img_url = tv.img_url
    end
  end

  def return_favorites
    array = []
    self.each do |object|
      if object.favorite == true
        array << object
      end
    end
    return array
  end

end

app/models/staff.rb
class Staff < ActiveRecord::Base
end

app/models/tv.rb
class Tv < ActiveRecord::Base
  belongs_to :project

  # after_save :check_for_and_create_favorite

  def change_favorite
    self.favorite = false if self.favorite = true
    self.favorite = true if self.favorite = false
  end

  def check_for_and_create_favorite
    if self.favorite == true && self.favorite_changed? == true
      Favorite.create(title: self.title,
                          year: self.year,
                   description: self.description,
                       img_url: self.img_url)
    elsif self.favorite == false && self.favorite_changed? == true
      favorite = Favorite.find_by(title: self.title,
                                   year: self.year,
                            description: self.description,
                                img_url: self.img_url)
      # favorite.destroy
    elsif
      self.favorite == true && self.favorite_changed? == false
      favorite = Favorite.find_by(title: self.title)

      favorite.update(title: self.title,
                        year: self.year,
                description: self.description,
                    img_url: self.img_url)
    end
  end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :set_film, only: [:show, :edit, :update, :destroy]

  def index
    @films = Film.all
  end

  def show
  end

  def new
    @film = Film.new
  end

  def edit
  end

  def create
    @film = Film.new(film_params)

    respond_to do |format|
      if @film.save
        format.html { redirect_to projects_url, notice: 'Film was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end


  def update
    # @film = Film.find_by(title: params[:title])
    # @film.update(film_params)
    respond_to do |format|
      if @film.update(film_params)
        format.html { redirect_to @film, notice: 'Film was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end


  def destroy
    @film.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Film was successfully destroyed.' }
    end
    # @film = Film.find_by(title: params[:title])
  end

  # def destroy
  #   @film= Film.find_by(title: params[:title])
  #   @film.destory

  #   redirect_to film_path
  # end

  private

  def set_film
    @film = Film.find(params[:id])
  end

  def film_params
    params.require(:film).permit(:title, :year, :distributor, :description, :img_url, :favorite)
  end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper

	def show_film
    @film = Film.find_by(title: params[:title])
  end


end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/staff_helper.rb
module StaffHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/tv_helper.rb
module TvHelper
end

app/views/films/_film_list.html.erb
<h1>Films</h1>
<div class="container project_frame">
  <div class="row valign">
		<% films.each do |film| %>
      <div class="col s12 m6 l3 center">
      <div class="poster_index">
        <%= link_to image_tag(film.img_url, :class => "poster_thumb"), film %>
      </div>
    	<div class="info">
      <div class="title_box">
        <h5>
          <% if film.favorite == true %>
            <span class="fa fa-star secondary"></span>
          <% end %>
          <%= truncate(film.title, :length => 50, :separator => ' ') %>
        </h5>
        <h6>
        <% if film.year == nil %>
        <%= "Coming Soon" %>
        <% end %>
        <%= film.year %>
        </h6>
      </div>
      </div>

      <div class="admin_box">
        <% if current_admin %>
          <%= link_to '<span class="fa fa-edit"></span> Edit'.html_safe, edit_film_path(film) %> |
          <%= link_to '<span class="fa fa-remove"></span> Remove'.html_safe, film, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </div>
    	</div>
    <% end %>
  </div>
</div>


<div class="admin_box">
  <% if current_admin %>
    <%= link_to'<span class="fa fa-plus"></span> New Film'.html_safe, new_film_path, :class => "btn valign" %>
  <% end %>
</div>

app/views/films/_form.html.erb
<%= form_for(@film) do |f| %>
  <% if @film.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@film.errors.count, "error") %> prohibited this film from being saved:</h2>
      <ul>
      <% @film.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="modal_box">
    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :year %><br>
      <%= f.text_field :year %>
    </div>
    <div class="field">
      <%= f.label :distributor %><br>
      <%= f.text_field :distributor %>
    </div>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_area :description,  class: "materialize-textarea" %>
    </div>
    <div class="field">
      <%= f.label :img_url %><br>
      <%= f.text_field :img_url %>
    </div>
    <div class="field center">
      <%= f.check_box :favorite, {:class => "filled-in"} %>
      <%= f.label :favorite %>
    </div>
    <div class="actions center">
      <%= f.submit "Save", class: "btn" %> or
      <%= link_to "Cancel", projects_url, class: "btn" %></div>
    </div>
  </div>
<% end %>

app/views/films/edit.html.erb
<div class="main_primary">
<h1 class="white-txt">Edit Film</h1>
	<div class="container-form">
	  <div class="form">
		<%= render 'form' %>
		<!-- <%= render "shared/formatting"  %> -->
		</div>
	</div>
</div>

app/views/films/new.html.erb
<div class="main_primary">
<h1 class="white-txt">New Film</h1>
	<div class="container-form">
	  <div class="form">
		<%= render 'form' %>
		<!-- <%= render "shared/formatting"  %> -->
		</div>
	</div>
</div>

app/views/films/show.html.erb
<div class="film_frame">
<div class="show_poster"><%= link_to image_tag(@film.img_url, :class => "poster")%></div>

<h1>
  <% if @film.favorite == true %>
    <span class="fa fa-star secondary"></span>
  <% end %>

 <div class="title_wrap"> <%= @film.title %> </div><span class="network_name"> (<%= @film.distributor %>)</span><br>

 <span class="year">  <%= @film.year %></span> </h1>

 <div class="divider"></div>
    <p> <%= markdown(@film.description) %> </p>

  <div class="divider"></div>

  <div class="admin_box">
    <%= link_to '<span class="fa fa-arrow-left"></span> Back'.html_safe, projects_path %>
    <% if current_admin %>
      | <%= link_to '<span class="fa fa-edit"></span> Edit'.html_safe, edit_film_path(@film) %>
      <% end %>
  </div>

</div>