config/routes.rb
Rails.application.routes.draw do

  get 'home/index'
  root "home#index"
  get 'home/services'

  get "projects", to: "projects#index"

  resources :clients
  resources :films
  resources :tvs
  resources :marketings
  resources :indie_films
  #resources :musicology_services
  resources :staffs
  resources :contacts, only: [:index]

  get "/login" => "sessions#new", as: "login"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy", as: "logout"

end

app/models/admin.rb
class Admin < ActiveRecord::Base

  has_secure_password

end

app/models/client.rb
class Client < ActiveRecord::Base
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
end

app/models/film.rb
class Film < ActiveRecord::Base
  belongs_to :project

  # after_save :check_for_and_create_favorite

  def change_favorite
    self.favorite = false if self.favorite = true
    self.favorite = true if self.favorite = false
  end

  def check_for_and_create_favorite
    if self.favorite == true && self.favorite_changed? == true
      Favorite.create(title: self.title,
                          year: self.year,
                   description: self.description,
                       img_url: self.img_url)
    elsif self.favorite == false && self.favorite_changed? == true
      favorite = Favorite.find_by(title: self.title,
                                   year: self.year,
                            description: self.description,
                                img_url: self.img_url)
      # favorite.destroy
    elsif
      self.favorite == true && self.favorite_changed? == false
      favorite = Favorite.find_by(title: self.title)

      favorite.update(title: self.title,
                        year: self.year,
                description: self.description,
                    img_url: self.img_url)
    end
  end
end

app/models/indie_film.rb
class IndieFilm < ActiveRecord::Base
end

app/models/marketing.rb
class Marketing < ActiveRecord::Base

  belongs_to :project
  after_save :check_for_and_create_favorite

  def change_favorite
    self.favorite = false if self.favorite = true
    self.favorite = true if self.favorite = false
  end

  def check_for_and_create_favorite
    if self.favorite == true && self.favorite_changed? == true
      Favorite.create(title: self.title,
                          year: self.year,
                   description: self.description,
                       img_url: self.img_url)
    elsif self.favorite == false && self.favorite_changed? == true
      favorite = Favorite.find_by(title: self.title,
                                   year: self.year,
                            description: self.description,
                                img_url: self.img_url)
      # favorite.destroy
    elsif
      self.favorite == true && self.favorite_changed? == false
      favorite = Favorite.find_by(title: self.title)
                  favorite.update(title: self.title,
                                   year: self.year,
                            description: self.description,
                                img_url: self.img_url)
    end
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
    has_many :tvs
    has_many :films
    has_many :marketings
    has_many :indie_films

    # def create_object(object)
    #   if object == "tv"
    #     self.tv.new(tv_params)
    #   elsif object == "film"
    #     self.tv.net(film_params)
    #   elsif object == "independednt_films"
    #     self.tv.net(independednt_films_params)
    # end

end

app/models/season.rb
class Season < ActiveRecord::Base
  belongs_to :tv
  before_save :check_image_url

  def check_image_url
    tv = Tv.find_by(id: self.tv_id)
    if self.img_url == nil
      self.img_url = tv.img_url
    end
  end

  def return_favorites
    array = []
    self.each do |object|
      if object.favorite == true
        array << object
      end
    end
    return array
  end

end

app/models/staff.rb
class Staff < ActiveRecord::Base
end

app/models/tv.rb
class Tv < ActiveRecord::Base
  belongs_to :project

  # after_save :check_for_and_create_favorite

  def change_favorite
    self.favorite = false if self.favorite = true
    self.favorite = true if self.favorite = false
  end

  def check_for_and_create_favorite
    if self.favorite == true && self.favorite_changed? == true
      Favorite.create(title: self.title,
                          year: self.year,
                   description: self.description,
                       img_url: self.img_url)
    elsif self.favorite == false && self.favorite_changed? == true
      favorite = Favorite.find_by(title: self.title,
                                   year: self.year,
                            description: self.description,
                                img_url: self.img_url)
      # favorite.destroy
    elsif
      self.favorite == true && self.favorite_changed? == false
      favorite = Favorite.find_by(title: self.title)

      favorite.update(title: self.title,
                        year: self.year,
                description: self.description,
                    img_url: self.img_url)
    end
  end
end

app/controllers/marketings_controller.rb
class MarketingsController < ApplicationController
  before_action :set_marketing, only: [:show, :edit, :update, :destroy]


  def index
    @marketings = Marketing.all
  end

  def show
  end


  def new
    @marketing = Marketing.new
  end


  def edit
  end


  def create
    @marketing = Marketing.new(marketing_params)

    respond_to do |format|
      if @marketing.save
        format.html { redirect_to @marketing, notice: 'Marketing Ad was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end


  def update
    respond_to do |format|
      if @marketing.update(marketing_params)
        format.html { redirect_to @marketing, notice: 'Marketing Ad was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @marketing.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Marketing Ad was successfully destroyed.' }
    end
  end

  private
    def set_marketing
      @marketing = Marketing.find(params[:id])
    end

    def marketing_params
      params.require(:marketing).permit(:year, :title, :distributor, :season, :description, :img_url, :favorite)
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/marketing_helper.rb
module MarketingHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper

	def show_film
    @film = Film.find_by(title: params[:title])
  end


end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/staff_helper.rb
module StaffHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/tv_helper.rb
module TvHelper
end

app/views/marketings/_form.html.erb
<%= form_for(@marketing) do |f| %>
  <% if @marketing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@marketing.errors.count, "error") %> prohibited this marketing from being saved:</h2>
      <ul>
      <% @marketing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="modal_box">
    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :year %><br>
      <%= f.text_field :year %>
    </div>
    <div class="field">
      <%= f.label :distributor %><br>
      <%= f.text_field :distributor %>
    </div>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_area :description,  class: "materialize-textarea" %>
    </div>
    <div class="field">
      <%= f.label :img_url %><br>
      <%= f.text_field :img_url %>
    </div>
    <div class="field center">
      <%= f.check_box :favorite, {:class => "filled-in"} %>
      <%= f.label :favorite %>
    </div>
    <div class="actions center">
      <%= f.submit "Save", class: "btn" %>  or  
      <%= link_to "Cancel", projects_url, class: "btn" %></div>
    </div>
  </div>
<% end %>

app/views/marketings/_index.html.erb
<h1>Marketing</h1>
  <div class="container project_frame">
    <div class="row valign">
      <% @marketings.each do |marketing| %>
        <div class="col s12 m6 l3 center">
        <div class="poster_index">
          <%= link_to image_tag(marketing.img_url, :class => "poster_thumb"), marketing %>
        </div>
        <div class="info">
          <div class="title_box">
          <h5>
          <% if marketing.favorite == true %>
            <span class="fa fa-star secondary"></span>
          <% end %>
          <%= truncate(marketing.title, :length => 50, :separator => ' ') %>
          </h5>

          <h6>
            <% if marketing.year == nil %>
              <%= "Coming Soon" %>
            <% end %>

            <%= marketing.year %>
          </h6>
        </div>
        </div>

        <div class="admin_box">
          <% if current_admin %>
            <%= link_to '<span class="fa fa-edit"></span> Edit'.html_safe, edit_marketing_path(marketing) %> |
            <%= link_to '<span class="fa fa-remove"></span> Remove'.html_safe, marketing, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </div>
        </div>
      <% end %>
    </div>
  </div>

<div class="admin_box">
  <% if current_admin %>
    <%=link_to '<span class="fa fa-plus"></span> New Marketing Ad'.html_safe, new_marketing_path, :class => "btn valign" %>
  <% end %>
</div>

app/views/marketings/edit.html.erb
<div class="main_primary">
<h1 class="white-txt">Edit Marketing Ad</h1>
	<div class="container-form">
	  <div class="form">
		<%= render 'form' %>
		<!-- <%= render "shared/formatting"  %> -->
		</div>
	</div>
</div>

app/views/marketings/new.html.erb
<div class="main_primary">
<h1 class="white-txt">New Marketing Ad</h1>
	<div class="container-form">
	  <div class="form">
		<%= render 'form' %>
		<!-- <%= render "shared/formatting"  %> -->
		</div>
	</div>
</div>

app/views/marketings/show.html.erb
<div class="film_frame">
<div class="show_poster"><%= link_to image_tag(@marketing.img_url, :class => "poster")%></div>

<h1>
  <% if @marketing.favorite == true %>
  <span class="fa fa-star secondary"></span>
  <% end %>
  <%= @marketing.title %> <br>
  <span class="network_name"> (<%= @marketing.distributor %>)</span><br>
<span class="year"> <%= @marketing.year %></span> </h1>
<div class="divider"></div>
<p> <%= markdown(@marketing.description) %> </p>

<div class="divider"></div>

<div class="admin_box">
  <%= link_to '<span class="fa fa-arrow-left"></span> Back'.html_safe, projects_path %>
  <% if current_admin %>
     | <%= link_to '<span class="fa fa-edit"></span> Edit'.html_safe, edit_marketing_path(@marketing) %>
  <% end %>
</div>

</div>