config/routes.rb
Rails.application.routes.draw do

  get 'home/index'
  root "home#index"
  get 'home/services'

  get "projects", to: "projects#index"

  resources :clients
  resources :films
  resources :tvs
  resources :marketings
  resources :indie_films
  #resources :musicology_services
  resources :staffs
  resources :contacts, only: [:index]

  get "/login" => "sessions#new", as: "login"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy", as: "logout"

end

app/models/admin.rb
class Admin < ActiveRecord::Base

  has_secure_password

end

app/models/client.rb
class Client < ActiveRecord::Base
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
end

app/models/film.rb
class Film < ActiveRecord::Base
  belongs_to :project

  # after_save :check_for_and_create_favorite

  def change_favorite
    self.favorite = false if self.favorite = true
    self.favorite = true if self.favorite = false
  end

  def check_for_and_create_favorite
    if self.favorite == true && self.favorite_changed? == true
      Favorite.create(title: self.title,
                          year: self.year,
                   description: self.description,
                       img_url: self.img_url)
    elsif self.favorite == false && self.favorite_changed? == true
      favorite = Favorite.find_by(title: self.title,
                                   year: self.year,
                            description: self.description,
                                img_url: self.img_url)
      # favorite.destroy
    elsif
      self.favorite == true && self.favorite_changed? == false
      favorite = Favorite.find_by(title: self.title)

      favorite.update(title: self.title,
                        year: self.year,
                description: self.description,
                    img_url: self.img_url)
    end
  end
end

app/models/indie_film.rb
class IndieFilm < ActiveRecord::Base
end

app/models/marketing.rb
class Marketing < ActiveRecord::Base

  belongs_to :project
  after_save :check_for_and_create_favorite

  def change_favorite
    self.favorite = false if self.favorite = true
    self.favorite = true if self.favorite = false
  end

  def check_for_and_create_favorite
    if self.favorite == true && self.favorite_changed? == true
      Favorite.create(title: self.title,
                          year: self.year,
                   description: self.description,
                       img_url: self.img_url)
    elsif self.favorite == false && self.favorite_changed? == true
      favorite = Favorite.find_by(title: self.title,
                                   year: self.year,
                            description: self.description,
                                img_url: self.img_url)
      # favorite.destroy
    elsif
      self.favorite == true && self.favorite_changed? == false
      favorite = Favorite.find_by(title: self.title)
                  favorite.update(title: self.title,
                                   year: self.year,
                            description: self.description,
                                img_url: self.img_url)
    end
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
    has_many :tvs
    has_many :films
    has_many :marketings
    has_many :indie_films

    # def create_object(object)
    #   if object == "tv"
    #     self.tv.new(tv_params)
    #   elsif object == "film"
    #     self.tv.net(film_params)
    #   elsif object == "independednt_films"
    #     self.tv.net(independednt_films_params)
    # end

end

app/models/season.rb
class Season < ActiveRecord::Base
  belongs_to :tv
  before_save :check_image_url

  def check_image_url
    tv = Tv.find_by(id: self.tv_id)
    if self.img_url == nil
      self.img_url = tv.img_url
    end
  end

  def return_favorites
    array = []
    self.each do |object|
      if object.favorite == true
        array << object
      end
    end
    return array
  end

end

app/models/staff.rb
class Staff < ActiveRecord::Base
end

app/models/tv.rb
class Tv < ActiveRecord::Base
  belongs_to :project

  # after_save :check_for_and_create_favorite

  def change_favorite
    self.favorite = false if self.favorite = true
    self.favorite = true if self.favorite = false
  end

  def check_for_and_create_favorite
    if self.favorite == true && self.favorite_changed? == true
      Favorite.create(title: self.title,
                          year: self.year,
                   description: self.description,
                       img_url: self.img_url)
    elsif self.favorite == false && self.favorite_changed? == true
      favorite = Favorite.find_by(title: self.title,
                                   year: self.year,
                            description: self.description,
                                img_url: self.img_url)
      # favorite.destroy
    elsif
      self.favorite == true && self.favorite_changed? == false
      favorite = Favorite.find_by(title: self.title)

      favorite.update(title: self.title,
                        year: self.year,
                description: self.description,
                    img_url: self.img_url)
    end
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper

	def show_film
    @film = Film.find_by(title: params[:title])
  end


end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/helpers/staff_helper.rb
module StaffHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/tv_helper.rb
module TvHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MCL Music Services</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <meta name="viewport" content="width=device-width,initial-scale=1.0" />
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
 <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">

  <%= csrf_meta_tags %>
</head>
<body>

  <header>
    <div class="bar">
    </div>
        <nav>
          <%= link_to image_tag("MCL-Logo-Orange-RGB.png", :class => 'brand-logo'), {action: :'index', :controller => 'home'} %>

          <div id="nav-trigger"><span class="trig"></span></div>
          <nav id="nav-main">
            <ul class="right">
              <li class="nav"><%= active_link_to '<span class="fa fa-home"></span> Home'.html_safe, home_index_path %></li>
              <!-- <li class="nav"><%= active_link_to "Services", home_services_path %></li> -->
              <li class="nav"><%= active_link_to "Clients", clients_path %></li>
              <li class="nav"><%= active_link_to "Projects", projects_path %></li>
              <li class="nav"><%= active_link_to "Staff", staffs_path %></li>
              <!-- class = nav    active_link_to 'musicology_services', MS_path-->
              <li class="nav"><%= active_link_to "Contacts", contacts_path %></li>
            </ul>
          </nav>
        <nav id="nav-mobile"></nav>
  </header>
  <div class="bar"></div>

<%= yield %>

<footer>
  <% if current_admin %>
    <%= link_to logout_path, :class => "admin-btn right", method: :delete do %>
      <span class="fa fa-unlock"></span>
    <% end %>
  <% else %>
    <a class="waves-effect waves-light modal-trigger admin-btn right" href="/login"><span class="fa fa-lock"></span></a>
  <% end %>
</footer>

	<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js"></script>
</body>
</html>

app/views/shared/_formatting.html.erb
<div class="info">
<h1>Formatting</h1>
<h5>Paragraphs</h5>
<p>Use two new lines to start a new paragraph.</p>
<h5><strong>Bold</strong></h5>
<p>**New** show title.</p>


<h5><em>Emphasis</em></h5>
<p>Titles should be *Italicized*.</p>


<h5>Lists</h5>
<p>Ingredients:

- Eggs
- Oil
- *Optional:* milk</p>


<h5>Links</h5>
<p>To download a PDF version of the recipe, [click here](https://example.com/scrambled-eggs.pdf).</p>

<h5>Images</h5>
<p>![The Finished Dish](https://example.com/eggs.png)</p>


</div>